### ISSUE TITLE
Requesting inclusion of the flows json

### ISSUE THREAD

**Issue by dwaiba** [zuhito/node-red-contrib-cognitive-services#12]

**Comment by zuhito** [comment]
Does it mean sample flow in import menu on Node-RED?
I'll consider about it. Thank you for your comment. :)

**Comment by dwaiba** [comment]
Thank You for this @zuhito .

**Comment by zuhito** [comment]
In the latest version of the module I added sample flows in node-red import-sample menu. Currently there are samples using only Vision APIs. As the next release, I'll add other example flows using other APIs. (Because Node-RED has some file path bug on Windows environment, users can import sample flows on Linux environment. I'll submit the bug into Node-RED issue.)
