### ISSUE TITLE
FR: ability to upload an image

### ISSUE THREAD

**Issue by pastukhov** [zuhito/node-red-contrib-cognitive-services#13]
Hello!
Please add ability to upload image instead of choosing an URL.
URL should be accessible from public network at it's not secure to grant public access to private video.

**Comment by zuhito** [comment]
Thank you for your comment. :) I understand your situation.
I think that you can already realize it in current Vision API's nodes because they support both "binary data" and URL string as their input.
You can input the binary data to Vision API nodes after uploading image file to Node-RED.
For example, "file inject" node in node-red-contrib-browser-utils will be useful to realize it.

- file inject node
https://flows.nodered.org/node/node-red-contrib-browser-utils

- Example flow data:
[{"id":"b1496791.6e8668","type":"debug","z":"5c1da831.62bc38","name":"","active":true,"console":"false","complete":"false","x":530,"y":360,"wires":[]},{"id":"9d4b905.724b77","type":"fileinject","z":"5c1da831.62bc38","name":"","x":180,"y":360,"wires":[["62f99af.8b1e764"]]},{"id":"62f99af.8b1e764","type":"Computer Vision","z":"5c1da831.62bc38","operation":"description","name":"","x":350,"y":360,"wires":[["b1496791.6e8668"]]}]
